name: Delete Stale Releases

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 5
          delete_tag_pattern: v3.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
