params ["_player"];
format["%1 called by %2 on %3", _fnc_scriptName, _fnc_scriptNameParent, (["Client", "Server"] select isServer)] call TRGM_GLOBAL_fnc_log;

if (_player != player) exitWith {};

private _missionInfo = createHashMapFromArray [
    ["TRGM_VAR_debugMessages", (if !(isNil "TRGM_VAR_debugMessages") then {TRGM_VAR_debugMessages;} else {"nil";})],
    ["TRGM_VAR_NeededObjectsAvailable", (if !(isNil "TRGM_VAR_NeededObjectsAvailable") then {TRGM_VAR_NeededObjectsAvailable;} else {"nil";})],
    ["TRGM_VAR_playerIsChoosingHQpos", (if !(isNil "TRGM_VAR_playerIsChoosingHQpos") then {TRGM_VAR_playerIsChoosingHQpos;} else {"nil";})],
    ["TRGM_VAR_HQPosFound", (if !(isNil "TRGM_VAR_HQPosFound") then {TRGM_VAR_HQPosFound;} else {"nil";})],
    ["TRGM_VAR_ManualAOPosFound", (if !(isNil "TRGM_VAR_ManualAOPosFound") then {TRGM_VAR_ManualAOPosFound;} else {"nil";})],
    ["TRGM_VAR_TopLeftPos", (if !(isNil "TRGM_VAR_TopLeftPos") then {TRGM_VAR_TopLeftPos;} else {"nil";})],
    ["TRGM_VAR_BotRightPos", (if !(isNil "TRGM_VAR_BotRightPos") then {TRGM_VAR_BotRightPos;} else {"nil";})],
    ["TRGM_VAR_aNVClassNames", (if !(isNil "TRGM_VAR_aNVClassNames") then {TRGM_VAR_aNVClassNames;} else {"nil";})],
    ["TRGM_VAR_FriendlySide", (if !(isNil "TRGM_VAR_FriendlySide") then {TRGM_VAR_FriendlySide;} else {"nil";})],
    ["TRGM_VAR_EnemySide", (if !(isNil "TRGM_VAR_EnemySide") then {TRGM_VAR_EnemySide;} else {"nil";})],
    ["TRGM_VAR_InsSide", (if !(isNil "TRGM_VAR_InsSide") then {TRGM_VAR_InsSide;} else {"nil";})],
    ["TRGM_VAR_FriendlySideString", (if !(isNil "TRGM_VAR_FriendlySideString") then {TRGM_VAR_FriendlySideString;} else {"nil";})],
    ["TRGM_VAR_EnemySideString", (if !(isNil "TRGM_VAR_EnemySideString") then {TRGM_VAR_EnemySideString;} else {"nil";})],
    ["TRGM_VAR_InsSideString", (if !(isNil "TRGM_VAR_InsSideString") then {TRGM_VAR_InsSideString;} else {"nil";})],
    ["TRGM_VAR_sArmaGroup", (if !(isNil "TRGM_VAR_sArmaGroup") then {TRGM_VAR_sArmaGroup;} else {"nil";})],
    ["TRGM_VAR_bNoVNChance", (if !(isNil "TRGM_VAR_bNoVNChance") then {TRGM_VAR_bNoVNChance;} else {"nil";})],
    ["TRGM_VAR_SideMissionMinDistFromBase", (if !(isNil "TRGM_VAR_SideMissionMinDistFromBase") then {TRGM_VAR_SideMissionMinDistFromBase;} else {"nil";})],
    ["TRGM_VAR_BaseAreaRange", (if !(isNil "TRGM_VAR_BaseAreaRange") then {TRGM_VAR_BaseAreaRange;} else {"nil";})],
    ["TRGM_VAR_KilledZoneRadius", (if !(isNil "TRGM_VAR_KilledZoneRadius") then {TRGM_VAR_KilledZoneRadius;} else {"nil";})],
    ["TRGM_VAR_KilledZoneInnerRadius", (if !(isNil "TRGM_VAR_KilledZoneInnerRadius") then {TRGM_VAR_KilledZoneInnerRadius;} else {"nil";})],
    ["TRGM_VAR_SaveZoneRadius", (if !(isNil "TRGM_VAR_SaveZoneRadius") then {TRGM_VAR_SaveZoneRadius;} else {"nil";})],
    ["TRGM_VAR_InitialBoxItems", (if !(isNil "TRGM_VAR_InitialBoxItems") then {TRGM_VAR_InitialBoxItems;} else {"nil";})],
    ["TRGM_VAR_InitialBoxItemsWithAce", (if !(isNil "TRGM_VAR_InitialBoxItemsWithAce") then {TRGM_VAR_InitialBoxItemsWithAce;} else {"nil";})],
    ["TRGM_VAR_CampaignRecruitUnitRifleman", (if !(isNil "TRGM_VAR_CampaignRecruitUnitRifleman") then {TRGM_VAR_CampaignRecruitUnitRifleman;} else {"nil";})],
    ["TRGM_VAR_CampaignRecruitUnitAT", (if !(isNil "TRGM_VAR_CampaignRecruitUnitAT") then {TRGM_VAR_CampaignRecruitUnitAT;} else {"nil";})],
    ["TRGM_VAR_CampaignRecruitUnitAA", (if !(isNil "TRGM_VAR_CampaignRecruitUnitAA") then {TRGM_VAR_CampaignRecruitUnitAA;} else {"nil";})],
    ["TRGM_VAR_CampaignRecruitUnitExplosiveSpecialist", (if !(isNil "TRGM_VAR_CampaignRecruitUnitExplosiveSpecialist") then {TRGM_VAR_CampaignRecruitUnitExplosiveSpecialist;} else {"nil";})],
    ["TRGM_VAR_CampaignRecruitUnitMedic", (if !(isNil "TRGM_VAR_CampaignRecruitUnitMedic") then {TRGM_VAR_CampaignRecruitUnitMedic;} else {"nil";})],
    ["TRGM_VAR_CampaignRecruitUnitEngineer", (if !(isNil "TRGM_VAR_CampaignRecruitUnitEngineer") then {TRGM_VAR_CampaignRecruitUnitEngineer;} else {"nil";})],
    ["TRGM_VAR_CampaignRecruitUnitAuto", (if !(isNil "TRGM_VAR_CampaignRecruitUnitAuto") then {TRGM_VAR_CampaignRecruitUnitAuto;} else {"nil";})],
    ["TRGM_VAR_CampaignRecruitUnitSniper", (if !(isNil "TRGM_VAR_CampaignRecruitUnitSniper") then {TRGM_VAR_CampaignRecruitUnitSniper;} else {"nil";})],
    ["TRGM_VAR_CampaignRecruitUnitSpotter", (if !(isNil "TRGM_VAR_CampaignRecruitUnitSpotter") then {TRGM_VAR_CampaignRecruitUnitSpotter;} else {"nil";})],
    ["TRGM_VAR_CampaignRecruitUnitUAV", (if !(isNil "TRGM_VAR_CampaignRecruitUnitUAV") then {TRGM_VAR_CampaignRecruitUnitUAV;} else {"nil";})],
    ["TRGM_VAR_GraveYardPos", (if !(isNil "TRGM_VAR_GraveYardPos") then {TRGM_VAR_GraveYardPos;} else {"nil";})],
    ["TRGM_VAR_GraveYardDirection", (if !(isNil "TRGM_VAR_GraveYardDirection") then {TRGM_VAR_GraveYardDirection;} else {"nil";})],
    ["TRGM_VAR_FriendlyFastResponseDingy", (if !(isNil "TRGM_VAR_FriendlyFastResponseDingy") then {TRGM_VAR_FriendlyFastResponseDingy;} else {"nil";})],
    ["TRGM_VAR_SmallTransportVehicle", (if !(isNil "TRGM_VAR_SmallTransportVehicle") then {TRGM_VAR_SmallTransportVehicle;} else {"nil";})],
    ["TRGM_VAR_EnemyRadioSounds", (if !(isNil "TRGM_VAR_EnemyRadioSounds") then {TRGM_VAR_EnemyRadioSounds;} else {"nil";})],
    ["TRGM_VAR_FriendlyRadioSounds", (if !(isNil "TRGM_VAR_FriendlyRadioSounds") then {TRGM_VAR_FriendlyRadioSounds;} else {"nil";})],
    ["TRGM_VAR_IEDClassNames", (if !(isNil "TRGM_VAR_IEDClassNames") then {TRGM_VAR_IEDClassNames;} else {"nil";})],
    ["TRGM_VAR_IEDFakeClassNames", (if !(isNil "TRGM_VAR_IEDFakeClassNames") then {TRGM_VAR_IEDFakeClassNames;} else {"nil";})],
    ["TRGM_VAR_ATMinesClassNames", (if !(isNil "TRGM_VAR_ATMinesClassNames") then {TRGM_VAR_ATMinesClassNames;} else {"nil";})],
    ["TRGM_VAR_WreckCarClasses", (if !(isNil "TRGM_VAR_WreckCarClasses") then {TRGM_VAR_WreckCarClasses;} else {"nil";})],
    ["TRGM_VAR_ChopperWrecks", (if !(isNil "TRGM_VAR_ChopperWrecks") then {TRGM_VAR_ChopperWrecks;} else {"nil";})],
    ["TRGM_VAR_MedicalMessItems", (if !(isNil "TRGM_VAR_MedicalMessItems") then {TRGM_VAR_MedicalMessItems;} else {"nil";})],
    ["TRGM_VAR_MedicalBoxes", (if !(isNil "TRGM_VAR_MedicalBoxes") then {TRGM_VAR_MedicalBoxes;} else {"nil";})],
    ["TRGM_VAR_ConesWithLight", (if !(isNil "TRGM_VAR_ConesWithLight") then {TRGM_VAR_ConesWithLight;} else {"nil";})],
    ["TRGM_VAR_Cones", (if !(isNil "TRGM_VAR_Cones") then {TRGM_VAR_Cones;} else {"nil";})],
    ["TRGM_VAR_TombStones", (if !(isNil "TRGM_VAR_TombStones") then {TRGM_VAR_TombStones;} else {"nil";})],
    ["TRGM_VAR_InformantImage", (if !(isNil "TRGM_VAR_InformantImage") then {TRGM_VAR_InformantImage;} else {"nil";})],
    ["TRGM_VAR_OfficerImage", (if !(isNil "TRGM_VAR_OfficerImage") then {TRGM_VAR_OfficerImage;} else {"nil";})],
    ["TRGM_VAR_WeaponDealerImage", (if !(isNil "TRGM_VAR_WeaponDealerImage") then {TRGM_VAR_WeaponDealerImage;} else {"nil";})],
    ["TRGM_VAR_AllInitScriptsFinished", (if !(isNil "TRGM_VAR_AllInitScriptsFinished") then {TRGM_VAR_AllInitScriptsFinished;} else {"nil";})],
    ["TRGM_VAR_AOCampOnlyAmmoBox", (if !(isNil "TRGM_VAR_AOCampOnlyAmmoBox") then {TRGM_VAR_AOCampOnlyAmmoBox;} else {"nil";})],
    ["TRGM_VAR_AODetails", (if !(isNil "TRGM_VAR_AODetails") then {TRGM_VAR_AODetails;} else {"nil";})],
    ["TRGM_VAR_ATFieldPos", (if !(isNil "TRGM_VAR_ATFieldPos") then {TRGM_VAR_ATFieldPos;} else {"nil";})],
    ["TRGM_VAR_ActiveTasks", (if !(isNil "TRGM_VAR_ActiveTasks") then {TRGM_VAR_ActiveTasks;} else {"nil";})],
    ["TRGM_VAR_AdminPlayer", (if !(isNil "TRGM_VAR_AdminPlayer") then {TRGM_VAR_AdminPlayer;} else {"nil";})],
    ["TRGM_VAR_AdvancedSettings", (if !(isNil "TRGM_VAR_AdvancedSettings") then {TRGM_VAR_AdvancedSettings;} else {"nil";})],
    ["TRGM_VAR_AllowAOFires", (if !(isNil "TRGM_VAR_AllowAOFires") then {TRGM_VAR_AllowAOFires;} else {"nil";})],
    ["TRGM_VAR_AllowUAVLocateHelp", (if !(isNil "TRGM_VAR_AllowUAVLocateHelp") then {TRGM_VAR_AllowUAVLocateHelp;} else {"nil";})],
    ["TRGM_VAR_BadPoints", (if !(isNil "TRGM_VAR_BadPoints") then {TRGM_VAR_BadPoints;} else {"nil";})],
    ["TRGM_VAR_BadPointsReason", (if !(isNil "TRGM_VAR_BadPointsReason") then {TRGM_VAR_BadPointsReason;} else {"nil";})],
    ["TRGM_VAR_CalledAirsupportIndex", (if !(isNil "TRGM_VAR_CalledAirsupportIndex") then {TRGM_VAR_CalledAirsupportIndex;} else {"nil";})],
    ["TRGM_VAR_CampaignInitiated", (if !(isNil "TRGM_VAR_CampaignInitiated") then {TRGM_VAR_CampaignInitiated;} else {"nil";})],
    ["TRGM_VAR_CheckPointAreas", (if !(isNil "TRGM_VAR_CheckPointAreas") then {TRGM_VAR_CheckPointAreas;} else {"nil";})],
    ["TRGM_VAR_CivDeathCount", (if !(isNil "TRGM_VAR_CivDeathCount") then {TRGM_VAR_CivDeathCount;} else {"nil";})],
    ["TRGM_VAR_ClearedPositions", (if !(isNil "TRGM_VAR_ClearedPositions") then {TRGM_VAR_ClearedPositions;} else {"nil";})],
    ["TRGM_VAR_CommsTowerPos", (if !(isNil "TRGM_VAR_CommsTowerPos") then {TRGM_VAR_CommsTowerPos;} else {"nil";})],
    ["TRGM_VAR_CoreCompleted", (if !(isNil "TRGM_VAR_CoreCompleted") then {TRGM_VAR_CoreCompleted;} else {"nil";})],
    ["TRGM_VAR_CurrentZeroMissionTitle", (if !(isNil "TRGM_VAR_CurrentZeroMissionTitle") then {TRGM_VAR_CurrentZeroMissionTitle;} else {"nil";})],
    ["TRGM_VAR_CustomObjectsSet", (if !(isNil "TRGM_VAR_CustomObjectsSet") then {TRGM_VAR_CustomObjectsSet;} else {"nil";})],
    ["TRGM_VAR_EnemyFactionData", (if !(isNil "TRGM_VAR_EnemyFactionData") then {TRGM_VAR_EnemyFactionData;} else {"nil";})],
    ["TRGM_VAR_EnemyID", (if !(isNil "TRGM_VAR_EnemyID") then {TRGM_VAR_EnemyID;} else {"nil";})],
    ["TRGM_VAR_FinalMissionStarted", (if !(isNil "TRGM_VAR_FinalMissionStarted") then {TRGM_VAR_FinalMissionStarted;} else {"nil";})],
    ["TRGM_VAR_FlareCounter", (if !(isNil "TRGM_VAR_FlareCounter") then {TRGM_VAR_FlareCounter;} else {"nil";})],
    ["TRGM_VAR_FireFlares", (if !(isNil "TRGM_VAR_FireFlares") then {TRGM_VAR_FireFlares;} else {"nil";})],
    ["TRGM_VAR_ForceEndSandStorm", (if !(isNil "TRGM_VAR_ForceEndSandStorm") then {TRGM_VAR_ForceEndSandStorm;} else {"nil";})],
    ["TRGM_VAR_ForceMissionSetup", (if !(isNil "TRGM_VAR_ForceMissionSetup") then {TRGM_VAR_ForceMissionSetup;} else {"nil";})],
    ["TRGM_VAR_HiddenPossitions", (if !(isNil "TRGM_VAR_HiddenPossitions") then {TRGM_VAR_HiddenPossitions;} else {"nil";})],
    ["TRGM_VAR_ISUNSUNG", (if !(isNil "TRGM_VAR_ISUNSUNG") then {TRGM_VAR_ISUNSUNG;} else {"nil";})],
    ["TRGM_VAR_InfTaskCount", (if !(isNil "TRGM_VAR_InfTaskCount") then {TRGM_VAR_InfTaskCount;} else {"nil";})],
    ["TRGM_VAR_InfTaskStarted", (if !(isNil "TRGM_VAR_InfTaskStarted") then {TRGM_VAR_InfTaskStarted;} else {"nil";})],
    ["TRGM_VAR_IntelFound", (if !(isNil "TRGM_VAR_IntelFound") then {TRGM_VAR_IntelFound;} else {"nil";})],
    ["TRGM_VAR_IntroMusic", (if !(isNil "TRGM_VAR_IntroMusic") then {TRGM_VAR_IntroMusic;} else {"nil";})],
    ["TRGM_VAR_IsFullMap", (if !(isNil "TRGM_VAR_IsFullMap") then {TRGM_VAR_IsFullMap;} else {"nil";})],
    ["TRGM_VAR_IsSnowMap", (if !(isNil "TRGM_VAR_IsSnowMap") then {TRGM_VAR_IsSnowMap;} else {"nil";})],
    ["TRGM_VAR_KilledPlayers", (if !(isNil "TRGM_VAR_KilledPlayers") then {TRGM_VAR_KilledPlayers;} else {"nil";})],
    ["TRGM_VAR_KilledPositions", (if !(isNil "TRGM_VAR_KilledPositions") then {TRGM_VAR_KilledPositions;} else {"nil";})],
    ["TRGM_VAR_LoadoutData", (if !(isNil "TRGM_VAR_LoadoutData") then {TRGM_VAR_LoadoutData;} else {"nil";})],
    ["TRGM_VAR_LoadoutDataDefault", (if !(isNil "TRGM_VAR_LoadoutDataDefault") then {TRGM_VAR_LoadoutDataDefault;} else {"nil";})],
    ["TRGM_VAR_MainMissionTitle", (if !(isNil "TRGM_VAR_MainMissionTitle") then {TRGM_VAR_MainMissionTitle;} else {"nil";})],
    ["TRGM_VAR_MaxBadPoints", (if !(isNil "TRGM_VAR_MaxBadPoints") then {TRGM_VAR_MaxBadPoints;} else {"nil";})],
    ["TRGM_VAR_MissionLoaded", (if !(isNil "TRGM_VAR_MissionLoaded") then {TRGM_VAR_MissionLoaded;} else {"nil";})],
    ["TRGM_VAR_MissionParamsSet", (if !(isNil "TRGM_VAR_MissionParamsSet") then {TRGM_VAR_MissionParamsSet;} else {"nil";})],
    ["TRGM_VAR_NewMissionMusic", (if !(isNil "TRGM_VAR_NewMissionMusic") then {TRGM_VAR_NewMissionMusic;} else {"nil";})],
    ["TRGM_VAR_ObjectivePossitions", (if !(isNil "TRGM_VAR_ObjectivePossitions") then {TRGM_VAR_ObjectivePossitions;} else {"nil";})],
    ["TRGM_VAR_OccupiedHousesPos", (if !(isNil "TRGM_VAR_OccupiedHousesPos") then {TRGM_VAR_OccupiedHousesPos;} else {"nil";})],
    ["TRGM_VAR_ParaDropped", (if !(isNil "TRGM_VAR_ParaDropped") then {TRGM_VAR_ParaDropped;} else {"nil";})],
    ["TRGM_VAR_PatrolType", (if !(isNil "TRGM_VAR_PatrolType") then {TRGM_VAR_PatrolType;} else {"nil";})],
    ["TRGM_VAR_PlayersHaveLeftStartingArea", (if !(isNil "TRGM_VAR_PlayersHaveLeftStartingArea") then {TRGM_VAR_PlayersHaveLeftStartingArea;} else {"nil";})],
    ["TRGM_VAR_ReinforcementsCalled", (if !(isNil "TRGM_VAR_ReinforcementsCalled") then {TRGM_VAR_ReinforcementsCalled;} else {"nil";})],
    ["TRGM_VAR_SaveType", (if !(isNil "TRGM_VAR_SaveType") then {TRGM_VAR_SaveType;} else {"nil";})],
    ["TRGM_VAR_SentryAreas", (if !(isNil "TRGM_VAR_SentryAreas") then {TRGM_VAR_SentryAreas;} else {"nil";})],
    ["TRGM_VAR_TimeLastReinforcementsCalled", (if !(isNil "TRGM_VAR_TimeLastReinforcementsCalled") then {TRGM_VAR_TimeLastReinforcementsCalled;} else {"nil";})],
    ["TRGM_VAR_TimeSinceAdditionalReinforcementsCalled", (if !(isNil "TRGM_VAR_TimeSinceAdditionalReinforcementsCalled") then {TRGM_VAR_TimeSinceAdditionalReinforcementsCalled;} else {"nil";})],
    ["TRGM_VAR_TimeSinceLastSpottedAction", (if !(isNil "TRGM_VAR_TimeSinceLastSpottedAction") then {TRGM_VAR_TimeSinceLastSpottedAction;} else {"nil";})],
    ["TRGM_VAR_ToUseMilitia_Side", (if !(isNil "TRGM_VAR_ToUseMilitia_Side") then {TRGM_VAR_ToUseMilitia_Side;} else {"nil";})],
    ["TRGM_VAR_bAndSoItBegins", (if !(isNil "TRGM_VAR_bAndSoItBegins") then {TRGM_VAR_bAndSoItBegins;} else {"nil";})],
    ["TRGM_VAR_bBaseHasChopper", (if !(isNil "TRGM_VAR_bBaseHasChopper") then {TRGM_VAR_bBaseHasChopper;} else {"nil";})],
    ["TRGM_VAR_bBreifingPrepped", (if !(isNil "TRGM_VAR_bBreifingPrepped") then {TRGM_VAR_bBreifingPrepped;} else {"nil";})],
    ["TRGM_VAR_bCommsBlocked", (if !(isNil "TRGM_VAR_bCommsBlocked") then {TRGM_VAR_bCommsBlocked;} else {"nil";})],
    ["TRGM_VAR_bHasCommsTower", (if !(isNil "TRGM_VAR_bHasCommsTower") then {TRGM_VAR_bHasCommsTower;} else {"nil";})],
    ["TRGM_VAR_bMortarFiring", (if !(isNil "TRGM_VAR_bMortarFiring") then {TRGM_VAR_bMortarFiring;} else {"nil";})],
    ["TRGM_VAR_bOptionsSet", (if !(isNil "TRGM_VAR_bOptionsSet") then {TRGM_VAR_bOptionsSet;} else {"nil";})],
    ["TRGM_VAR_iAllowNVG", (if !(isNil "TRGM_VAR_iAllowNVG") then {TRGM_VAR_iAllowNVG;} else {"nil";})],
    ["TRGM_VAR_iCampaignDay", (if !(isNil "TRGM_VAR_iCampaignDay") then {TRGM_VAR_iCampaignDay;} else {"nil";})],
    ["TRGM_VAR_iMissionParamObjective", (if !(isNil "TRGM_VAR_iMissionParamObjective") then {TRGM_VAR_iMissionParamObjective;} else {"nil";})],
    ["TRGM_VAR_iMissionParamObjective2", (if !(isNil "TRGM_VAR_iMissionParamObjective2") then {TRGM_VAR_iMissionParamObjective2;} else {"nil";})],
    ["TRGM_VAR_iMissionParamObjective3", (if !(isNil "TRGM_VAR_iMissionParamObjective3") then {TRGM_VAR_iMissionParamObjective3;} else {"nil";})],
    ["TRGM_VAR_iMissionParamRepOption", (if !(isNil "TRGM_VAR_iMissionParamRepOption") then {TRGM_VAR_iMissionParamRepOption;} else {"nil";})],
    ["TRGM_VAR_iMissionParamType", (if !(isNil "TRGM_VAR_iMissionParamType") then {TRGM_VAR_iMissionParamType;} else {"nil";})],
    ["TRGM_VAR_iStartLocation", (if !(isNil "TRGM_VAR_iStartLocation") then {TRGM_VAR_iStartLocation;} else {"nil";})],
    ["TRGM_VAR_iUseRevive", (if !(isNil "TRGM_VAR_iUseRevive") then {TRGM_VAR_iUseRevive;} else {"nil";})],
    ["TRGM_VAR_iWeather", (if !(isNil "TRGM_VAR_iWeather") then {TRGM_VAR_iWeather;} else {"nil";})]
];

private _outputString = "[";
{
    _outputString = format["%1%2[%3,%4],", _outputString, "\r\n", _x, _y];
} forEach _missionInfo;
_outputString = format["%1%2%3", _outputString, "\r\n", "]"];
copyToClipboard _outputString;
[localize "STR_TRGM2_logMissionInfo_copied"] call TRGM_GLOBAL_fnc_notify;

true;